'use strict';
const KEY='sem-filtro-v1',app=document.querySelector('#app');
let game=null,interval=null,selection=CATEGORIES.map(c=>c.id),chaos=true;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(game))}catch{toast('O navegador não permitiu salvar. A partida continua nesta aba.')}}
function load(){try{const g=JSON.parse(localStorage.getItem(KEY));
const valid=g&&g.version===1&&Array.isArray(g.players)&&g.players.length===2&&g.players.every(p=>typeof p.name==='string'&&p.name.length<=24&&Number.isFinite(p.score)&&p.score>=0)&&Array.isArray(g.categories)&&g.categories.length&&g.categories.every(id=>CATEGORIES.some(c=>c.id===id))&&[0,1].includes(g.turn)&&['ready','secret','running','expired','result','won','empty'].includes(g.phase)&&Array.isArray(g.used)&&g.used.every(id=>CARDS.some(c=>c.id===id))&&[30,45,60,90].includes(g.seconds)&&[10,15,20,30].includes(g.target)&&Number.isInteger(g.round)&&g.round>0;
if(!valid)return;
if(!['ready','empty'].includes(g.phase)){const canonical=CARDS.find(c=>c.id===g.card?.id);if(!canonical)return;g.card=canonical}
if(g.phase==='running'&&!Number.isFinite(g.deadline))return;
game=g;if(game.phase==='secret'){game.phase='ready';game.used=game.used.filter(id=>id!==game.card.id);game.card=null;save()}
}catch{game=null}}
function home(){clearInterval(interval);app.className='';app.innerHTML=`<section class="hero"><div><div class="eyebrow">MÍMICA PARA QUEM JÁ PAGA BOLETO</div><h1>Menos filtro.<br><em>Mais mímica.</em></h1><p>A vida adulta já é uma comédia. Agora tenta explicar isso sem abrir a boca.</p><div class="eyebrow"><span class="count">${CARDS.length} CARTAS</span> · 2 PESSOAS · ZERO JUÍZO</div></div><div class="art" aria-hidden="true"><div class="mini-card"><small>SEM FILTRO</small></div><div class="mini-card front"><small>MODO CAOS</small><div class="glyph">✳</div><b>A dignidade<br>fica pra depois.</b></div></div></section><section class="panel"><h2>Quem vai passar vergonha?</h2><p class="sub">Uma carta secreta. Um celular. Muitas interpretações duvidosas.</p>${game?'<button class="secondary" id="resume">↗ Continuar partida salva</button><p class="hint">Iniciar outra partida substitui o placar salvo.</p><br>':''}<form id="setup"><div class="fields"><label>Jogador 1<input name="p1" value="Alain" maxlength="24" required autocomplete="off"></label><label>Jogador 2<input name="p2" value="Gabi" maxlength="24" required autocomplete="off"></label><label>Tempo da rodada<select name="time"><option value="30">30 segundos</option><option value="45" selected>45 segundos</option><option value="60">60 segundos</option><option value="90">90 segundos</option></select></label><label>Meta de pontos<select name="target"><option value="10">10 pontos</option><option value="15">15 pontos</option><option value="20">20 pontos</option><option value="30">30 pontos</option></select></label></div><div class="section-label">O QUE ENTRA NA MISTURA?</div><div class="chips"><button type="button" class="chip selected" id="chaos" aria-pressed="true">✳ Caos · tudo misturado</button>${CATEGORIES.map(c=>`<button type="button" class="chip selected" data-category="${c.id}" aria-pressed="true">${c.icon} ${c.name}</button>`).join('')}</div><label class="toggle"><input type="checkbox" name="repeat" checked>Não repetir cartas nesta partida</label><p class="hint" id="poolcount"></p><button class="primary" style="margin-top:20px">Bora passar vergonha →</button><p class="hint">+18 tem insinuações e situações íntimas. Desmarque se preferir.</p></form></section><div class="rules"><div><b>01.</b>Quem faz a mímica olha a carta sozinho.</div><div><b>02.</b>Esconde, inicia e passa o celular. Sem falar!</div><div><b>03.</b>Acerto pontua para quem fez a mímica. Alternem.</div></div>`;
 selection=CATEGORIES.map(c=>c.id);chaos=true;updateChips();document.querySelector('#resume')?.addEventListener('click',render);
 document.querySelector('#chaos').onclick=()=>{chaos=true;selection=CATEGORIES.map(c=>c.id);updateChips()};
 document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{chaos=false;selection=selection.includes(b.dataset.category)?selection.filter(id=>id!==b.dataset.category):[...selection,b.dataset.category];updateChips()});
 document.querySelector('#setup').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),names=[f.get('p1').trim(),f.get('p2').trim()];if(names.some(n=>!n))return toast('Preencha os dois nomes.');if(!selection.length)return toast('Escolha pelo menos uma categoria.');game={version:1,players:names.map(name=>({name,score:0})),seconds:Number(f.get('time')),target:Number(f.get('target')),categories:[...selection],noRepeat:f.has('repeat'),turn:0,round:1,phase:'ready',card:null,used:[],deadline:null};save();render()};}
function updateChips(){document.querySelector('#chaos').classList.toggle('selected',chaos);document.querySelector('#chaos').setAttribute('aria-pressed',chaos);document.querySelectorAll('[data-category]').forEach(b=>{const selected=selection.includes(b.dataset.category);b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)});document.querySelector('#poolcount').textContent=`${CARDS.filter(c=>selection.includes(c.category)).length} cartas na mistura · categoria e dificuldade ficam secretas.`}
function draw(){const pool=CARDS.filter(c=>game.categories.includes(c.category)&&(!game.noRepeat||!game.used.includes(c.id)));if(!pool.length){game.phase='empty';save();render();return}game.card=pool[Math.floor(Math.random()*pool.length)];game.used.push(game.card.id);game.phase='secret';save();render()}
function start(){game.phase='running';game.deadline=Date.now()+game.seconds*1000;save();render()}
function finish(hit){if(game.phase!=='running'&&game.phase!=='expired')return;if(game.phase==='running'&&Date.now()>=game.deadline){game.phase='expired';hit=false}if(game.phase==='expired')hit=false;clearInterval(interval);game.hit=hit;game.players[game.turn].score+=hit?game.card.points:0;game.phase=game.players[game.turn].score>=game.target?'won':'result';save();render()}
function next(){game.turn=1-game.turn;game.round++;game.phase='ready';game.card=null;game.deadline=null;save();render()}
function render(){clearInterval(interval);if(!game)return home();app.className='game';const p=game.players[game.turn];app.innerHTML=`<div class="scoreboard">${game.players.map((p,i)=>`${i?'<div class="versus">×</div>':''}<div class="score ${game.turn===i?'active':''}"><span>${esc(p.name)}</span><strong>${p.score}</strong></div>`).join('')}</div><div class="round-label">RODADA ${game.round} · META ${game.target} PONTOS</div><div id="stage"></div><button class="textbutton" id="back">Configurações / início</button>`;document.querySelector('#back').onclick=()=>{if(game.phase==='running'&&!confirm('Voltar ao início? O cronômetro continuará correndo.'))return;home()};const s=document.querySelector('#stage');
 if(game.phase==='ready'){s.innerHTML=`<div class="playcard"><span class="symbol">🤫</span><div class="badge">SÓ QUEM FAZ A MÍMICA PODE OLHAR</div><h2>Passa o celular<br>para ${esc(p.name)}.</h2><p>A outra pessoa vira o rosto. A categoria também é segredo.</p></div><div class="actions"><button class="primary" id="reveal">Estou sozinho. Revelar carta →</button></div>`;document.querySelector('#reveal').onclick=draw}
 if(game.phase==='secret'){const c=CATEGORIES.find(c=>c.id===game.card.category);s.innerHTML=`<div class="playcard secret"><div class="badge">${c.icon} ${c.name} · ${['','Fácil','Média','Difícil'][game.card.points]} · ${game.card.points} PT${game.card.points>1?'S':''}</div><h2>${esc(game.card.text)}</h2><p>Memoriza. Nada de falar ou mostrar a carta!</p></div><div class="actions"><button class="primary" id="start">Esconder e começar · ${game.seconds}s →</button></div>`;document.querySelector('#start').onclick=start}
 if(['running','expired'].includes(game.phase)){s.innerHTML=`<div class="playcard"><div class="badge">${esc(p.name)} FAZ A MÍMICA</div><div class="timer" id="timer" role="timer"></div><div class="track" aria-hidden="true"><span id="progress"></span></div><p id="timerhint">A carta está escondida. Valendo!</p></div><div class="actions"><button class="primary" id="hit">Acertou ✓</button><button class="secondary" id="pass">Passar →</button></div><p class="hint">Vale acertar a ideia, não precisa repetir a frase exata.</p>`;document.querySelector('#hit').onclick=()=>finish(true);document.querySelector('#pass').onclick=()=>finish(false);tick();if(game.phase==='running')interval=setInterval(tick,200)}
 if(['result','won'].includes(game.phase)){const won=game.phase==='won';s.innerHTML=`<div class="playcard"><span class="symbol">${won?'🏆':game.hit?'🙌':'🫠'}</span><div class="badge">${won?'VITÓRIA SEM FILTRO':game.hit?'ACERTOU! +'+game.card.points+' PONTOS':'ESSA FICOU PARA A HISTÓRIA'}</div><h2>${won?`<span class="winner">${esc(p.name)} venceu!</span>`:esc(game.card.text)}</h2><p>${won?'Mímica duvidosa. Vitória indiscutível.':game.hit?'Pontos para quem fez a mímica. Agora troquem!':'Sem pontos desta vez. A próxima é de vocês.'}</p>${won?`<p>Última carta: ${esc(game.card.text)}</p>`:''}</div><div class="actions"><button class="primary" id="next">${won?'Jogar de novo ↻':'Próxima · vez de '+esc(game.players[1-game.turn].name)+' →'}</button></div>`;document.querySelector('#next').onclick=won?()=>{game.players.forEach(p=>p.score=0);game.turn=0;game.round=1;game.used=[];game.phase='ready';game.card=null;save();render()}:next}
 if(game.phase==='empty'){s.innerHTML='<div class="playcard"><span class="symbol">🎴</span><h2>Vocês zeraram o baralho!</h2><p>Todas as cartas selecionadas já saíram. Embaralhe de novo mantendo o placar.</p></div><div class="actions"><button class="primary" id="reshuffle">Embaralhar novamente ↻</button></div>';document.querySelector('#reshuffle').onclick=()=>{game.used=[];game.phase='ready';save();render()}}
}
function tick(){const remaining=game.phase==='expired'?0:Math.max(0,Math.ceil((game.deadline-Date.now())/1000));document.querySelector('#timer').textContent=String(remaining).padStart(2,'0');document.querySelector('#timer').classList.toggle('low',remaining<=10);document.querySelector('#progress').style.width=remaining/game.seconds*100+'%';if(remaining===0){clearInterval(interval);if(game.phase!=='expired'){game.phase='expired';save();navigator.vibrate?.([120,80,120])}document.querySelector('#timerhint').textContent='Tempo esgotado! Esta rodada não pontua.';document.querySelector('#hit').disabled=true;document.querySelector('#pass').textContent='Ver carta e continuar →'}}
load();home();
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
