/* Cartas originais. Edite os textos ou adicione novas entradas em qualquer categoria. */
const CATEGORIES = [
 {id:'cotidiano',name:'Cotidiano',icon:'☕',description:'O drama nosso de cada dia'},
 {id:'vergonha',name:'Vergonha alheia',icon:'🫣',description:'Queria desaparecer agora'},
 {id:'casal',name:'Casal',icon:'💘',description:'Amor, ciúme e divisão do edredom'},
 {id:'adulto',name:'+18 / Safadeza',icon:'🌶️',description:'Duplo sentido, zero timidez'},
 {id:'bebida',name:'Bebedeira',icon:'🍸',description:'A dignidade ficou no bar'},
 {id:'boletos',name:'Vida adulta',icon:'💸',description:'Ser adulto foi uma cilada'},
 {id:'absurdo',name:'Situações absurdas',icon:'🪩',description:'Não tente encontrar lógica'}
];
const RAW_CARDS = {
 cotidiano: `Tentando matar uma barata voadora|Abrindo um pote impossível|Procurando o celular que está na sua mão|Tomando banho quando a água fica gelada|Pisando numa peça de brinquedo descalço|Tentando dormir com um mosquito no ouvido|Carregando todas as sacolas numa viagem só|Tirando uma calça apertada|Comendo algo quente sem poder cuspir|Pegando um sabonete que não para de escorregar|Tentando espirrar sem conseguir|Procurando o lado certo do lençol com elástico|Limpando uma janela e percebendo que a sujeira está do outro lado|Passando fio dental e ficando preso|Montando um móvel e sobrando parafusos|Fazendo exercício e fingindo que não está morrendo|Tirando uma selfie e derrubando o celular no rosto|Espantando um gato do teclado|Tentando abrir uma embalagem com os dentes|Fugindo da chuva com uma sacola na cabeça|Ouvindo áudio com o celular grudado no ouvido|Tentando colocar uma capa no edredom|Enfiando uma linha minúscula na agulha|Trocando a roupa dentro de um carro|Batendo um tapete e levando toda a poeira na cara|Procurando os óculos sem os óculos|Tentando caminhar com um chinelo arrebentado|Cozinhando e disparando o alarme de fumaça|Pegando uma coisa que caiu atrás do sofá|Desentupindo uma pia e comemorando cedo demais`,
 vergonha: `Mandando beijo para quem cumprimentava a pessoa atrás|Acenando para alguém que não era seu conhecido|Disfarçando um peido no elevador|Sendo pego olhando pelo buraco da fechadura|Tropeçando e transformando o tropeço em corrida|Cantando o refrão errado com muita confiança|Dando um abraço quando a pessoa queria um aperto de mão|Entrando numa porta de vidro fechada|Tentando sair de fininho e derrubando uma cadeira|Rindo numa hora completamente inadequada|Fingindo entender uma conversa em outra língua|Deixando o celular tocar no silêncio total|Dançando sem perceber que todo mundo parou|Saindo do banheiro com papel preso no sapato|Tentando puxar uma porta que é de empurrar|Confundindo um manequim com um vendedor|Mostrando uma foto e alguém deslizando para a próxima|Fingindo que estava alongando depois de cair|Sendo flagrado ensaiando uma pose no espelho|Tentando lembrar o nome de alguém durante o abraço|Fazendo carinho num cachorro que rosna|Aplaudindo antes de todo mundo|Tirando um cochilo e acordando com a própria ronqueira|Fingindo gostar de uma comida horrível|Percebendo uma etiqueta pendurada na roupa|Sendo pego dançando na câmera de uma reunião|Tentando esconder uma mancha de suor|Falhando ao tentar sentar numa cadeira que girou|Tentando tirar uma foto discreta e disparando o flash|Chamando um estranho achando que era seu parceiro`,
 casal: `Roubando o edredom durante a madrugada|Fingindo dormir para não levantar|Tentando espiar a conversa do parceiro|Pedindo desculpa sem saber pelo quê|Escolhendo um filme e ninguém concordando|Tentando roncar menos depois de uma cutucada|Dividindo a última batata frita com muita má vontade|Dando um abraço enquanto o outro lava a louça|Disputando o lado da cama|Fazendo massagem e cansando em dez segundos|Sentindo ciúmes e fingindo tranquilidade|Esperando o outro se arrumar para sair|Tentando explicar um sonho absurdo ao acordar|Pedindo carinho sem admitir|Mostrando uma roupa nova e esperando elogio|Fingindo não ver a louça suja|Tentando beijar com o nariz entupido|Brigando com o GPS durante uma viagem a dois|Provando a comida do parceiro antes de pedir a sua|Tentando se reconciliar oferecendo comida|Esquentando os pés gelados no outro|Fingindo que não comeu o chocolate guardado|Posando para a milésima foto do passeio|Dando dicas óbvias do presente que quer|Acordando assustado com o outro roncando|Tentando sair da cama sem acordar o parceiro|Fazendo uma surpresa romântica e derrubando tudo|Levando um café na cama e derramando|Montando uma barraca a dois sem se entender|Disputando espaço no sofá com um gato`,
 adulto: `Tentando colocar uma camisinha e se atrapalhando|Dançando sensualmente e sentindo uma câimbra|Mandando uma foto ousada e se arrependendo|Tentando tirar um sutiã e não achando o fecho|Ensaiando uma pose sedutora no espelho|Flertando e recebendo só um aperto de mão|Tentando beijar alguém e batendo os dentes|Ouvindo os vizinhos numa noite animada|Escondendo um brinquedo íntimo antes de uma visita|Tentando fazer cara sexy e espirrando|Fazendo striptease e ficando preso na camiseta|Percebendo que a câmera estava ligada ao trocar de roupa|Tentando ser discreto ao comprar camisinha|Desfilando de roupão como se fosse lingerie|Chegando para seduzir e encontrando o outro dormindo|Passando perfume demais antes de um encontro|Tentando dar uma piscadinha e piscando os dois olhos|Recebendo uma mensagem safada no meio da reunião|Escondendo um chupão antes de sair|Tentando tirar uma bota durante um momento romântico|Ensaiando uma cantada sem usar palavras|Fazendo uma dança no colo e perdendo o equilíbrio|Arrumando a cama às pressas quando a campainha toca|Procurando a roupa espalhada depois de um encontro|Tentando abrir uma garrafa para criar clima e espirrando tudo|Fingindo inocência depois de uma piada de duplo sentido|Tentando manter a pose com uma lingerie desconfortável|Fazendo uma entrada sensual e tropeçando no tapete|Descobrindo que o espelho do motel é no teto|Saindo de um encontro e comemorando escondido`,
 bebida: `Tentando provar que não está bêbado|Abraçando um poste achando que é um amigo|Dançando com um copo cheio sem derramar|Tentando colocar a chave na fechadura depois da festa|Cantando no karaokê como uma estrela internacional|Procurando o equilíbrio num barco imaginário|Tomando um shot e fingindo que foi suave|Acordando de ressaca com a luz no rosto|Prometendo que nunca mais vai beber|Tentando comer um lanche gigante de madrugada|Tirando o sapato e andando com ele na mão|Pedindo água como se estivesse no deserto|Tentando sair numa foto e fechando os olhos|Dançando sentado porque não consegue levantar|Descobrindo que o copo está vazio|Tentando contar dinheiro no balcão do bar|Fazendo amizade com um desconhecido em cinco segundos|Sentindo o chão girar ao deitar|Tentando beber água sem sair da cama|Carregando um amigo que pesa mais que você|Jogando sinuca e acertando só o ar|Tentando andar em linha reta com muita concentração|Fazendo brinde e quebrando o próprio copo|Confundindo o carro do aplicativo com outro|Tentando pedir um lanche com o celular invertido|Acordando sem lembrar onde deixou os sapatos|Virando DJ da festa sem ninguém pedir|Dando um discurso emocionado para uma planta|Tentando subir num banquinho como se fosse um palco|Fazendo pose de sóbrio enquanto a cadeira gira`,
 boletos: `Vendo o valor da fatura do cartão|Procurando dinheiro no bolso e achando um boleto|Fingindo trabalhar quando o chefe aparece|Entrando numa reunião sem perceber que o microfone está aberto|Montando um currículo com muita autoconfiança|Tentando entender a declaração de imposto|Recebendo salário e vendo tudo desaparecer|Comparando preços no mercado com uma calculadora|Tentando consertar um vazamento e piorando|Esperando atendimento por telefone por uma eternidade|Descobrindo um fio de cabelo branco|Lendo um contrato e fingindo entender|Tentando negociar um desconto só com o olhar|Acordando antes do despertador num dia de folga|Regando uma planta que já morreu|Recebendo uma entrega enquanto está no banho|Subindo escadas depois de meses sem exercício|Tentando manter a calma com a internet caindo|Vendo o preço de um apartamento|Tentando impressionar numa entrevista de emprego|Saindo da cadeira depois de oito horas sentado|Fazendo marmita e esquecendo em casa|Procurando a garantia de um aparelho quebrado|Tentando falar numa reunião com a câmera congelada|Descobrindo que a roupa encolheu na lavagem|Fazendo compras com fome e enchendo o carrinho|Tentando acordar numa segunda-feira|Desmarcando um compromisso para ficar no sofá|Tentando economizar energia apagando todas as luzes|Celebrando quando um exame dá tudo normal`,
 absurdo: `Um dinossauro tentando arrumar a cama|Um vampiro passando protetor solar|Um zumbi numa entrevista de emprego|Um astronauta com vontade de ir ao banheiro|Uma sereia tentando usar uma esteira|Um robô apaixonado com curto-circuito|Uma galinha tentando fazer yoga|Um fantasma tentando assustar alguém distraído|Um super-herói preso no trânsito|Uma múmia tentando trocar o lençol|Um alienígena experimentando pimenta|Um pinguim num desfile de moda|Um lobisomem indo ao depilador|Um polvo tentando vestir oito mangas|Um ninja com soluço|Um unicórnio preso numa porta giratória|Uma estátua com coceira no nariz|Um mágico que faz o próprio dinheiro sumir|Um jacaré tentando escovar os dentes|Um pirata com enjoo no barco|Um gigante tentando entrar num carro pequeno|Uma bruxa que perdeu o controle da vassoura|Um peixe tentando aprender a nadar|Um caranguejo tentando andar para frente|Um dragão tentando apagar as velas do bolo|Um cavaleiro tentando abraçar de armadura|Um gato fingindo ser gerente de uma empresa|Um cupido errando todas as flechas|Uma árvore tentando fugir de um cachorro|Um papai noel preso na chaminé`
};
const CARDS = Object.entries(RAW_CARDS).flatMap(([category,raw])=>raw.split('|').map((text,i)=>({id:category+'-'+i,category,text,points: i<10?1:i<20?2:3})));
if(typeof module !== 'undefined') module.exports={CARDS,CATEGORIES};
